//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRPO_Mouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class library_book_example
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public library_book_example()
        {
            this.library_books_relation = new HashSet<library_books_relation>();
        }
    
        public int inventory_number { get; set; }
        public int book_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public bool present { get; set; }
        public Nullable<System.DateTime> date_in { get; set; }
        public Nullable<System.DateTime> date_return { get; set; }
    
        public virtual library_users library_users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<library_books_relation> library_books_relation { get; set; }
    }
}
