//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRPO_Mouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class library_sessions
    {
        public int id { get; set; }
        public int userId { get; set; }
        public string AccessToken { get; set; }
        public string RefreshToken { get; set; }
        public System.DateTime CreateAt { get; set; }
        public System.DateTime ExpiresIn { get; set; }
    
        public virtual library_users library_users { get; set; }
    }
}
