//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRPO_Mouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class library_users_data
    {
        public int user_id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public System.DateTime birth_date { get; set; }
        public string phone_number { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public int house_number { get; set; }
        public Nullable<int> apartment_number { get; set; }
        public string passport_series { get; set; }
        public string passport_number { get; set; }
    
        public virtual library_users library_users { get; set; }
    }
}
