//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRPO_Mouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class library_books
    {
        public int id { get; set; }
        public string ISBN { get; set; }
        public string title { get; set; }
        public int author { get; set; }
        public string genre { get; set; }
        public string publisher { get; set; }
        public string publication_place { get; set; }
        public System.DateTime publication_year { get; set; }
        public int pages { get; set; }
        public decimal price { get; set; }
    
        public virtual library_authors library_authors { get; set; }
    }
}
