//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRPO_Mouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class library_books_relation
    {
        public string ISBN { get; set; }
        public int inv_number { get; set; }
    
        public virtual library_book_example library_book_example { get; set; }
    }
}
